<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ciudad;

class CiudadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ciudades = [
            ['Arica', 1],
            ['Camarones', 1],
            ['Putre', 2],
            ['General Lagos', 2],
            ['Iquique', 3],
            ['Alto Hospicio', 3],
            ['Pozo Almonte', 4],
            ['Camiña', 4],
            ['Colchane', 4],
            ['Huara', 4],
            ['Pica', 4],
            ['Antofagasta', 5],
            ['Mejillones', 5],
            ['Sierra Gorda', 5],
            ['Taltal', 5],
            ['Calama', 6],
            ['Ollague', 6],
            ['San Pedro De Atacama', 6],
            ['Tocopilla', 7],
            ['María Elena', 7],
            ['Copiapó', 8],
            ['Caldera', 8],
            ['Tierra Amarilla', 8],
            ['Chañaral', 9],
            ['Diego De Almagro', 9],
            ['Vallenar', 10],
            ['Alto Del Carmen', 10],
            ['Freirina', 10],
            ['Huasco', 10],
            ['La Serena', 11],
            ['Coquimbo', 11],
            ['Andacollo', 11],
            ['La Higuera', 11],
            ['Paiguano', 11],
            ['Vicuña', 11],
            ['Illapel', 12],
            ['Canela', 12],
            ['Los Vilos', 12],
            ['Salamanca', 12],
            ['Ovalle', 13],
            ['Combarbalá', 13],
            ['Monte Patria', 13],
            ['Punitaqui', 13],
            ['Río Hurtado', 13],
            ['Valparaíso', 14],
            ['Casablanca', 14],
            ['Concón', 14],
            ['Juan Fernández', 14],
            ['Puchuncaví', 14],
            ['Quintero', 14],
            ['Viña Del Mar', 14],
            ['Isla De Pascua', 15],
            ['Los Andes', 16],
            ['Calle Larga', 16],
            ['Rinconada', 16],
            ['San Esteban', 16],
            ['La Ligua', 17],
            ['Cabildo', 17],
            ['Papudo', 17],
            ['Petorca', 17],
            ['Zapallar', 17],
            ['Quillota', 18],
            ['Calera', 18],
            ['Hijuelas', 18],
            ['La Cruz', 18],
            ['Nogales', 18],
            ['San Antonio', 19],
            ['Algarrobo', 19],
            ['Cartagena', 19],
            ['El Quisco', 19],
            ['El Tabo', 19],
            ['Santo Domingo', 19],
            ['San Felipe', 20],
            ['Catemu', 20],
            ['Llaillay', 20],
            ['Panquehue', 20],
            ['Putaendo', 20],
            ['Santa María', 20],
            ['Quilpué', 21],
            ['Limache', 21],
            ['Olmué', 21],
            ['Villa Alemana', 21],
            ['Santiago', 22],
            ['Cerrillos', 22],
            ['Cerro Navia', 22],
            ['Conchalí', 22],
            ['El Bosque', 22],
            ['Estación Central', 22],
            ['Huechuraba', 22],
            ['Independencia', 22],
            ['La Cisterna', 22],
            ['La Florida', 22],
            ['La Granja', 22],
            ['La Pintana', 22],
            ['La Reina', 22],
            ['Las Condes', 22],
            ['Lo Barnechea', 22],
            ['Lo Espejo', 22],
            ['Lo Prado', 22],
            ['Macul', 22],
            ['Maipú', 22],
            ['Ñuñoa', 22],
            ['Pedro Aguirre Cerda', 22],
            ['Peñalolén', 22],
            ['Providencia', 22],
            ['Pudahuel', 22],
            ['Quilicura', 22],
            ['Quinta Normal', 22],
            ['Recoleta', 22],
            ['Renca', 22],
            ['San Joaquín', 22],
            ['San Miguel', 22],
            ['San Ramón', 22],
            ['Vitacura', 22],
            ['Puente Alto', 23],
            ['Pirque', 23],
            ['San José De Maipo', 23],
            ['Colina', 24],
            ['Lampa', 24],
            ['Tiltil', 24],
            ['San Bernardo', 25],
            ['Buin', 25],
            ['Calera De Tango', 25],
            ['Paine', 25],
            ['Melipilla', 26],
            ['Alhué', 26],
            ['Curacaví', 26],
            ['María Pinto', 26],
            ['San Pedro', 26],
            ['Talagante', 27],
            ['El Monte', 27],
            ['Isla De Maipo', 27],
            ['Padre Hurtado', 27],
            ['Peñaflor', 27],
            ['Rancagua', 28],
            ['Codegua', 28],
            ['Coinco', 28],
            ['Coltauco', 28],
            ['Doñihue', 28],
            ['Graneros', 28],
            ['Las Cabras', 28],
            ['Machali', 28],
            ['Malloa', 28],
            ['Mostazal', 28],
            ['El Olivar', 28],
            ['Peumo', 28],
            ['Pichidegua', 28],
            ['Quinta De Tilcoco', 28],
            ['Rengo', 28],
            ['Requinoa', 28],
            ['San Vicente', 28],
            ['Pichilemu', 29],
            ['La Estrella', 29],
            ['Litueche', 29],
            ['Marchihue', 29],
            ['Navidad', 29],
            ['Paredones', 29],
            ['San Fernando', 30],
            ['Chépica', 30],
            ['Chimbarongo', 30],
            ['Lolol', 30],
            ['Nancagua', 30],
            ['Palmilla', 30],
            ['Peralillo', 30],
            ['Placilla', 30],
            ['Pumanque', 30],
            ['Santa Cruz', 30],
            ['Talca', 31],
            ['Constitución', 31],
            ['Curepto', 31],
            ['Empedrado', 31],
            ['Maule', 31],
            ['Pelarco', 31],
            ['Pencahue', 31],
            ['Río Claro', 31],
            ['San Clemente', 31],
            ['San Rafael', 31],
            ['Cauquenes', 32],
            ['Chanco', 32],
            ['Pelluhue', 32],
            ['Curicó', 33],
            ['Hualañe', 33],
            ['Licantén', 33],
            ['Molina', 33],
            ['Rauco', 33],
            ['Romeral', 33],
            ['Sagrada Familia', 33],
            ['Teno', 33],
            ['Vichuquén', 33],
            ['Linares', 34],
            ['Colbún', 34],
            ['Longaví', 34],
            ['Parral', 34],
            ['Retiro', 34],
            ['San Javier', 34],
            ['Villa Alegre', 34],
            ['Yerbas Buenas', 34],
            ['Chillán', 35],
            ['Bulnes', 35],
            ['Chillán Viejo', 35],
            ['El Carmen', 35],
            ['Pemuco', 35],
            ['Pinto', 35],
            ['Quillón', 35],
            ['San Ignacio', 35],
            ['Yungay', 35],
            ['Quirihue', 36],
            ['Cobquecura', 36],
            ['Coelemu', 36],
            ['Ninhue', 36],
            ['Portezuelo', 36],
            ['Ranquil', 36],
            ['Treguaco', 36],
            ['San Carlos', 37],
            ['Coihueco', 37],
            ['Ñiquén', 37],
            ['San Fabián', 37],
            ['San Nicolás', 37],
            ['Concepción', 38],
            ['Coronel', 38],
            ['Chiguayante', 38],
            ['Florida', 38],
            ['Hualqui', 38],
            ['Lota', 38],
            ['Penco', 38],
            ['San Pedro de la Paz', 38],
            ['Santa Juana', 38],
            ['Talcahuano', 38],
            ['Tomé', 38],
            ['Hualpén', 38],
            ['Lebu', 39],
            ['Arauco', 39],
            ['Cañete', 39],
            ['Contulmo', 39],
            ['Curanilahue', 39],
            ['Los Alamos', 39],
            ['Tirua', 39],
            ['Los Angeles', 40],
            ['Antuco', 40],
            ['Cabrero', 40],
            ['Laja', 40],
            ['Mulchén', 40],
            ['Nacimiento', 40],
            ['Negrete', 40],
            ['Quilaco', 40],
            ['Quilleco', 40],
            ['San Rosendo', 40],
            ['Santa Bárbara', 40],
            ['Tucapel', 40],
            ['Yumbel', 40],
            ['Alto Biobío', 40],
            ['Temuco', 41],
            ['Carahue', 41],
            ['Cunco', 41],
            ['Curarrehue', 41],
            ['Freire', 41],
            ['Galvarino', 41],
            ['Gorbea', 41],
            ['Lautaro', 41],
            ['Loncoche', 41],
            ['Melipeuco', 41],
            ['Nueva Imperial', 41],
            ['Padre Las Casas', 41],
            ['Perquenco', 41],
            ['Pitrufquén', 41],
            ['Pucón', 41],
            ['Saavedra', 41],
            ['Teodoro Schmidt', 41],
            ['Toltén', 41],
            ['Vilcún', 41],
            ['Villarrica', 41],
            ['Cholchol', 41],
            ['Angol', 42],
            ['Collipulli', 42],
            ['Curacautín', 42],
            ['Ercilla', 42],
            ['Lonquimay', 42],
            ['Los Sauces', 42],
            ['Lumaco', 42],
            ['Puren', 42],
            ['Renaico', 42],
            ['Traiguén', 42],
            ['Victoria', 42],
            ['Valdivia', 43],
            ['Corral', 43],
            ['Lanco', 43],
            ['Los Lagos', 43],
            ['Máfil', 43],
            ['Mariquina', 43],
            ['Paillaco', 43],
            ['Panguipulli', 43],
            ['La Unión', 44],
            ['Futrono', 44],
            ['Lago Ranco', 44],
            ['Río Bueno', 44],
            ['Puerto Montt', 45],
            ['Calbuco', 45],
            ['Cochamó', 45],
            ['Fresia', 45],
            ['Frutillar', 45],
            ['Los Muermos', 45],
            ['Llanquihue', 45],
            ['Maullín', 45],
            ['Puerto Varas', 45],
            ['Castro', 46],
            ['Ancud', 46],
            ['Chonchi', 46],
            ['Curaco de Velez', 46],
            ['Dalcahue', 46],
            ['Puqueldón', 46],
            ['Queilén', 46],
            ['Quellón', 46],
            ['Quemchi', 46],
            ['Quinchao', 46],
            ['Osorno', 47],
            ['Puerto Octay', 47],
            ['Purranque', 47],
            ['Puyehue', 47],
            ['Río Negro', 47],
            ['San Juan de la Costa', 47],
            ['San Pablo', 47],
            ['Chaitén', 48],
            ['Futaleufú', 48],
            ['Hualaihue', 48],
            ['Palena', 48],
            ['Coihayque', 49],
            ['Lago Verde', 49],
            ['Aisén', 50],
            ['Cisnes', 50],
            ['Guaitecas', 50],
            ['Cochrane', 51],
            ['O\'Higgins', 51],
            ['Tortel', 51],
            ['Chile Chico', 52],
            ['Río Ibáñez', 52],
            ['Punta Arenas', 53],
            ['Laguna Blanca', 53],
            ['Río Verde', 53],
            ['San Gregorio', 53],
            ['Cabo de Hornos', 54],
            ['Antártica', 54],
            ['Porvenir', 55],
            ['Primavera', 55],
            ['Timaukel', 55],
            ['Natales', 56],
            ['Torres del Paine', 56],
        ];

        $ciudades = array_map(function ($ciudad) {
            return [
                'ciudad_nombre' => $ciudad[0],
                'provincia_id' => $ciudad[1],
            ];
        }, $ciudades);

        Ciudad::insert($ciudades);
    }
}
