<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DiscoDuro;

class DiscoDuroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $discos = [
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Nombre pulento 1',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1]
        ];

    $discos = array_map(function ($disco, $index) {
        return [
            'disco_duro_memoria' => rand(1,8)*1000,
            'disco_duro_nombre' => $disco[1] . ($index + 1),
            'disco_duro_foto' => (string)rand(1,3) . '.jpg',
            'disco_duro_crystaldisk' => 'Crystaldisk.jpg',
            'disco_duro_horas_encendido' => $disco[3],
            'disco_duro_esperanza_vida' => $disco[4],
            'disco_duro_precio' => rand(1,100)*500 + 10000,
            'disponibilidad_id' => rand(1,2),
            'almacen_id' => $disco[7],
            'estado_id' => rand(1,4),
            'tamano_id' => rand(1,2),
            'marca_id' => rand(1,7),
            'sistema_archivos_id' => rand(1,2),
            'tipo_entrada_id' => 6,
        ];
    }, $discos, array_keys($discos));

        DiscoDuro::insert($discos);
    }
}
