<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Periferico;

class PerifericoSeeder extends Seeder
{
    public function run(): void
    {
        $perifericos = [
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion del periferico',
            9999,
            1,
            1,
            1,
            1,
            1,
            1]
        ];

        $perifericos = array_map(function ($periferico) {
            return [
                'periferico_nombre' => "Periferico pulento",
                'periferico_foto' => 'periferico'.(string)rand(1,3) . '.jpg',
                'periferico_descripcion' => $periferico[0],
                'periferico_precio' => rand(1,100)*500 + 10000,
                'disponibilidad_id' => $periferico[2],
                'almacen_id' => $periferico[3],
                'estado_id' => $periferico[4],
                'marca_id' => rand(1,7),
                'tipo_entrada_id' => $periferico[6],
                'tipo_periferico_id' => $periferico[7],
            ];
        }, $perifericos);

        Periferico::insert($perifericos);
    }
}
