<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ram;

class RamSeeder extends Seeder
{
    public function run(): void
    {
        $ram= [
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            9999,
            1,
            1,
            1,
            1,
            1,
            1,
            1]
        ];
        $ram= array_map(function ($ram) {
            return [
                'ram_descripcion' => $ram[0],
                'ram_nombre' => "Ram pulenta",
                'ram_foto' => 'ram_'.(string)rand(1,4) . '.jpg',
                'ram_precio' => rand(1,100)*500 + 10000,
                'disponibilidad_id' => rand(1,2),
                'almacen_id' => 1,
                'estado_id' => rand(1,3),
                'marca_id' => rand(1,7),
                'tipo_ram_id' => $ram[6],
                'CapacidadRam_id' => rand(1,5),
                'tamano_ram_id' => $ram[7],
                'velocidad_ram_id' => $ram[8],
            ];
        }, $ram);

        Ram::insert($ram);
    }
}
