<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class seeder_periferico extends Seeder
{
    public function run(): void
    {
        $perifericos = [
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0],
            ['Drescripcion del periferico',
            0,
            0,
            0,
            0,
            0,
            0]
        ];

        $perifericos = array_map(function ($periferico) {
            return [
                'periferico_descripcion' => $periferico[0],
                'disponibilidad_id' => $periferico[1],
                'almacen_id' => $periferico[2],
                'estado_id' => $periferico[3],
                'marca_id' => $periferico[4],
                'tipo_entrada_id' => $periferico[5],
                'tipo_periferico_id' => $periferico[6],
            ];
        }, $perifericos);

        periferico::insert($perifericos);
    }
}
