<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ram;

class seeder_ram extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rams = [
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Drescripcion de la ram',
            1,
            1,
            1,
            1,
            1,
            1,
            1]
        ];
        $rams = array_map(function ($ram) {
            return [
                'ram_descripcion' => $ram[0],
                'disponibilidad_id' => $ram[1],
                'almacen_id' => $ram[2],
                'estado_id' => $ram[3],
                'marca_id' => $ram[4],
                'tipo_ram_id' => $ram[5],
                'tamano_ram_id' => $ram[6],
                'velocidad_ram_id' => $ram[7],
            ];
        }, $rams);

        ram::insert($rams);
    }
}
