<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\disco_duro;

class seeder_disco_duro extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $discos = [
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1],
            ['Memoria',
            'Crystaldisk',
            'Horas de encendido',
            'Espenaza de vida',
            9999,
            1,
            1,
            1,
            1,
            1,
            1]
        ];

        $discos = array_map(function ($disco) {
            return [
                'disco_duro_memoria' => $disco[0],
                'disco_duro_crystaldisk' => $disco[1],
                'disco_duro_horas_encendido' => $disco[2],
                'disco_duro_esperanza_vida' => $disco[3],
                'disco_duro_precio' => $disco[4],
                'disponibilidad_id' => $disco[5],
                'almacen_id' => $disco[6],
                'estado_id' => $disco[7],
                'tamano_id' => $disco[8],
                'marca_id' => $disco[9],
                'sistema_archivos_id' => $disco[10],
            ];
        }, $discos);

        disco_duro::insert($discos);
    }
}
